### ISSUE TITLE
0.4.0 roadmap

### ISSUE THREAD

**Issue by chrislit** [chrislit/abydos#101]
New feature tasks:
- [x] additions to ConfusionTable (#148)
- [x] Waahlin (#102)
- [x] Ozbay (#103)

Project management issues:
- [x] I think we can switch to Apache/BSD/MIT maybe LGPL? (#55)
- [x] Need to implement some tokenizers (and make q-grams part of this); SyllabiPy?; whitespace; NLTK?
- ~~[ ] more regtests (#96)~~ moved to 0.4.1

Distance metrics:
- [x] extended Sift4 (#62)
- [x] fuzzy set distances (#71)
- ~~[ ] degraded hamming (#77)~~ moved to 0.4.1
- [x] soft similarity (#78)
- [x] bag & set alternatives of set distances (#79)
- [x] add qval/skip range/iter to set distances (#90)
- [x] remaining set distances defined in http://www.iiisci.org/journal/CV$/sci/pdfs/GS315JG.pdf
- [x] correct doctests
- [x] get tests working on Python 2.7
- [x] add tokenizer doctests

Release:
- [x] clear TODOs
- [x] all CIs building
- [x] update notebooks
- [x] new DOI
- [x] tag release
- [x] build releases
- [x] PyPI
- [x] conda-forge

**Comment by chrislit** [comment]
Pending successful completion of the stress test in a couple days, 0.4.0 may be complete.
