### ISSUE TITLE
0.7 roadmap

### ISSUE THREAD

**Issue by chrislit** [chrislit/abydos#279]
Phonetic algorithms:
- [ ] Henry code(?) (#73)
- [ ] Rees/Taxamatch (#168)
- [ ] Rosenfelder's English phoneticization (#84)
- [ ] #277

Distance measures:
- [ ] re-org distance classes (#189)
- [ ] Token Levenshtein (#202)
- [ ] Cormode's compression distance (#167)
- [ ] Laver distances (#164)
- [ ] ALINE with Double (#205)
- [ ] Ipadist (#218)

Stemmers:
(I'm on the fence about whether stemmers should be added or deferred to other projects)
- [ ] KSTEM (#44)
- [ ] Snowball stemmers (#34)
- [ ] Kraaij/Pohlmann (#64)
- [ ] CLEF (#61)

Release:
- [ ] remove deprecated items due for removal
- [ ] maximize test coverage
- [ ] clear Issues
- [ ] clear TODOs
- [ ] all CIs building
- [ ] update notebooks
- [ ] new DOI
- [ ] tag release
- [ ] build releases
- [ ] PyPI
- [ ] conda-forge
- [ ] check docs
